[[Libksba]]
arch = "aarch64"
git-tree-sha1 = "02b76f574b38ea704f897ff6fb2b67bd94359692"
os = "macos"

    [[Libksba.download]]
    sha256 = "73bb6cfe8038999b03bc6b7ee17a044a947e24919cd4017a4f2537b36eff677b"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.aarch64-apple-darwin.tar.gz"
[[Libksba]]
arch = "aarch64"
git-tree-sha1 = "5cb463acb51278639a80ec14abf40340332a5864"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "16fccdf85b5548edfb88ba6daf2e0f78301b7bf0df75794b8e7cef08b7274fff"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.aarch64-linux-gnu.tar.gz"
[[Libksba]]
arch = "aarch64"
git-tree-sha1 = "029ffdb75da45ff127b1781d7a438bca9b441455"
libc = "musl"
os = "linux"

    [[Libksba.download]]
    sha256 = "e876a2f2675cfde2e91d57d7a59d73c1a53ea31637f633e7c75ac94b8ece312f"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.aarch64-linux-musl.tar.gz"
[[Libksba]]
arch = "aarch64"
git-tree-sha1 = "6b097a1a249fe53dd8405dfa7e848faac6e77603"
os = "freebsd"

    [[Libksba.download]]
    sha256 = "361b4e998b26bd06c5d15c3db1f2c5586c444f602f44ea70e33421717d218bf2"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.aarch64-unknown-freebsd.tar.gz"
[[Libksba]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "77c2822ef7efe003594f3237f1f6f852f31648e0"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "04f9ac21d2937316cd0471b003a0380a1bff7089042061308e4ce3b20b1cab80"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.armv6l-linux-gnueabihf.tar.gz"
[[Libksba]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6cce586c60b492c614077d9ef4c30faddc3b94e9"
libc = "musl"
os = "linux"

    [[Libksba.download]]
    sha256 = "96c8b7e3de0e64b67e7e2228a6375aa1e7e60c6041c787e20338356783553e94"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.armv6l-linux-musleabihf.tar.gz"
[[Libksba]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "65a93d3559be7cdd36d7b2e431fac3d19a1f5e39"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "4b1ea1d5ec27a92e3f260e4a8a69963133d0d84bb99aa88acdb48731ee35d23c"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.armv7l-linux-gnueabihf.tar.gz"
[[Libksba]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "980c87185e884dacb92c3344b7dd2ee533457a33"
libc = "musl"
os = "linux"

    [[Libksba.download]]
    sha256 = "075fe975595150fe33e2b203e5df053a634abb3d1aa6bde4f1be7f13c6665a2a"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.armv7l-linux-musleabihf.tar.gz"
[[Libksba]]
arch = "i686"
git-tree-sha1 = "8d0ec63bce833d53f3c4dd104f3f3b00a8ffccd8"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "324d68fa647dad8d589284b179cdff60c483c97e24a71962753cc46693109f1d"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.i686-linux-gnu.tar.gz"
[[Libksba]]
arch = "i686"
git-tree-sha1 = "46ff3e8d346521e7521eb0eb0b7319702b816608"
libc = "musl"
os = "linux"

    [[Libksba.download]]
    sha256 = "d51aee519641f663f3ac4af61af61ee7d290042274f4f856534d83b3792a9ea8"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.i686-linux-musl.tar.gz"
[[Libksba]]
arch = "i686"
git-tree-sha1 = "d4848af0af37bad672ceefff5996237572369169"
os = "windows"

    [[Libksba.download]]
    sha256 = "91d3dd2de663d71f819303e1373203f519d8376cf4cfb7f5aec70745dd1bf7a4"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.i686-w64-mingw32.tar.gz"
[[Libksba]]
arch = "powerpc64le"
git-tree-sha1 = "fb1d40364176dc494dae374912d2bc32776adc55"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "689ba6fceb66d88a5ea0142d845dcf8d0631eab4700007f8d5c816e5e17c0fe3"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.powerpc64le-linux-gnu.tar.gz"
[[Libksba]]
arch = "riscv64"
git-tree-sha1 = "06d513622710cd4504c0f2e0736e304351371f1d"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "660b485c9306a21e8acb683ff47fe0257115e2c4fd30be4fa6e7d40953b0d005"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.riscv64-linux-gnu.tar.gz"
[[Libksba]]
arch = "x86_64"
git-tree-sha1 = "c42da30fd5cf08786bee2481057e8f55944d0a09"
os = "macos"

    [[Libksba.download]]
    sha256 = "3f0cbee1da7d47b4dc31484198cacd13f26376dbe504a3ea2ceba3e3a5bacfd8"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.x86_64-apple-darwin.tar.gz"
[[Libksba]]
arch = "x86_64"
git-tree-sha1 = "3a72798557d7e5e6e469c25a5cbcf35b87cf2549"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "46e3c7d94ff56f2d70d61190953abf511b91c55e41ab75c0ae3acbadb126f90b"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.x86_64-linux-gnu.tar.gz"
[[Libksba]]
arch = "x86_64"
git-tree-sha1 = "045bcaf009460c054a287cb4e0ea653982552288"
libc = "musl"
os = "linux"

    [[Libksba.download]]
    sha256 = "a0479fa8278f21c913342ff6c689836c7b87d7d9b71182b427adb7f909f5a36c"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.x86_64-linux-musl.tar.gz"
[[Libksba]]
arch = "x86_64"
git-tree-sha1 = "8735d7d9dbaf4fbb013c0748c40463ea7881f231"
os = "freebsd"

    [[Libksba.download]]
    sha256 = "466df7740cc7119b7212929ca00b1680a78414294a8c848246dcb9a14ecc2a27"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.x86_64-unknown-freebsd.tar.gz"
[[Libksba]]
arch = "x86_64"
git-tree-sha1 = "ede475ef4bc8866bbf11f28f64aacc06cb838091"
os = "windows"

    [[Libksba.download]]
    sha256 = "a541d8b7fb86f949262683a5b3aa68d65d0a56ab443649aad1d146acacde4849"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.9+0/Libksba.v1.6.9.x86_64-w64-mingw32.tar.gz"
